version: "3.3"
services:
  iroha:
    build:
      context: ./
      dockerfile: Dockerfile.debug
    image: iroha:debug
    environment:
      TORII_URL: iroha:1337
      MAX_FAULTY_PEERS: 0
      BLOCK_TIME_MS: 1000
      COMMIT_TIME_MS: 1500
      TX_RECEIPT_TIME_MS: 1000
      IROHA_TRUSTED_PEERS: '[{"address":"iroha:1337", "public_key": {"inner": [101, 170, 80, 164, 103, 38, 73, 61, 223, 133, 83, 139, 247, 77, 176, 84, 117, 15, 22, 28, 155, 125, 80, 226, 40, 26, 61, 248, 40, 159, 58, 53]}}]'
    ports:
      - "1337:1337"
